-- Initial PostgreSQL schema. Safe to run again; existing records are preserved.
BEGIN;
CREATE TABLE IF NOT EXISTS "cases" (
  "_id" TEXT PRIMARY KEY,
  "caseNumber" TEXT NOT NULL UNIQUE,
  "caseType" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "assignedOfficer" TEXT NOT NULL,
  "courtDate" TIMESTAMPTZ NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "criminals" (
  "_id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL,
  "age" DOUBLE PRECISION NOT NULL,
  "gender" TEXT NOT NULL,
  "address" TEXT NOT NULL,
  "crimeType" TEXT NOT NULL,
  "arrestDate" TIMESTAMPTZ NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "evidence" (
  "_id" TEXT PRIMARY KEY,
  "evidenceName" TEXT NOT NULL,
  "evidenceType" TEXT NOT NULL,
  "collectedDate" TIMESTAMPTZ NOT NULL,
  "caseNumber" TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "firs" (
  "_id" TEXT PRIMARY KEY,
  "firNumber" TEXT NOT NULL UNIQUE,
  "date" TIMESTAMPTZ NOT NULL,
  "policeStation" TEXT NOT NULL,
  "complainantName" TEXT NOT NULL,
  "crimeType" TEXT NOT NULL,
  "description" TEXT,
  "status" TEXT DEFAULT 'Open',
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "personnel" (
  "_id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL,
  "rank" TEXT NOT NULL,
  "department" TEXT NOT NULL,
  "contactNumber" TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
